### ISSUE TITLE
add license to each file

### ISSUE THREAD

**Issue by ks6088ts** [Azure-Samples/jp-azureopenai-samples#13]
Run the following command to add license

```shell
$ addlicense -f LICENSE.md .
```

ref. https://github.com/google/addlicense

**Comment by ks6088ts** [comment]
`addlicense` doesn't support `.bicep` so far, thus I forked and applied patch to it.
https://github.com/ks6088ts/addlicense

**Comment by rukasakurai** [comment]
Closing this Issue since
- We have https://github.com/Azure-Samples/jp-azureopenai-samples/blob/main/LICENSE.md
- While it would be better to put at two line license comment on each of the files we wrote, I think we need to do this on a sample by sample basis (1~6), and I think it will be difficult to keep track of it using this GitHub Issue
